deployment:
  tasks:
    - export DEPLOYPATH=/home/acd1f4ftwarecom/repositories/turkticaret_casestudy_2
    - cd $DEPLOYPATH
    - git pull https://github.com/ademcaniyik/turkticaret_casestudy_2.git main
